/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import Classes.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlphaLegends
 */
public class IUBuscaProfundidade extends javax.swing.JFrame {

    private int tipo;
    private MatrizAdjacencia MA;
    ListaAdjacencia[] LA;
    DefaultTableModel model = new DefaultTableModel(); //pegar seu model aqui
    JTable JTable1 = new JTable(model);
//ou table.setModel(model);
    /**
     * Creates new form IUBuscaProfundidade
     **/
    
    public IUBuscaProfundidade(){
        initComponents();

    }
    
    public IUBuscaProfundidade(MatrizAdjacencia MA) {
        initComponents(); 
        tipo = 1;
        this.MA = MA;
    }
    
    public IUBuscaProfundidade(ListaAdjacencia[] LA) {
        initComponents();
        tipo = 2;
        this.LA = LA;
    }
    
    //Busca Matriz Adjacencia
    
    public void BuscaProfundidadeMatriz(MatrizAdjacencia MA){
        int raiz = Integer.valueOf(Raiz.getText());
        int[][] matriz = MA.getMatriz();
        int[] cor = new int[matriz.length];
        int[] d = new int[matriz.length];
        int[] f = new int[matriz.length];
        for(int i=0;i<matriz.length;i++){
            cor[i] = 0; //0 = branco
        }
        int tempo = 0;
        for(int i=raiz;i<matriz.length;i++){
            for(int j=0;j<matriz.length;j++){
                if(matriz[i][j]!=Integer.MAX_VALUE){
                    if(cor[i]==0){
                      VisitaBuscaMatriz(i,cor,d,f,matriz,tempo);
                    }
                    
                }
            }
        }
        for(int i=0;i<d.length;i++){
            model.addRow(new Object[]{Arrays.hashCode(matriz[i]), d[Arrays.hashCode(matriz[i])], f[Arrays.hashCode(matriz[i])]});
        }
        
        
        
    }
    
    //Busca com Lista Adjacencia

    public void BuscaProfundidadeLista(ListaAdjacencia[] LA){
        int raiz = Integer.valueOf(Raiz.getText());
        int[] cor = new int[LA.length];
        int[] d = new int[LA.length];
        int[] f = new int[LA.length];
        for(int i=0;i<LA.length;i++){
            cor[i] = 0; //0 = branco
        }
        int tempo=0;
        for(int i=raiz;i<LA.length;i++){
            if(cor[LA[i].getVertice()]==0){
                VisitaBuscaLista(i,cor,d,f,LA,tempo);
            }  
        }
        for(int i=0;i<d.length;i++){
            model.addRow(new Object[]{ LA[i].getVertice(), d[LA[i].getVertice()], f[LA[i].getVertice()]});
        }
    }
    
    //Auxiliar para Matriz Adjacencia
    
    public void VisitaBuscaMatriz(int u,int[] cor,int[] d,int[] f,int[][] matriz,int tempo){
        cor[u] = 1;//1 = cinza
        tempo++;
        d[u]=tempo;
        for(int k=0;k<matriz.length;k++){
            if(matriz[u][k]!=Integer.MAX_VALUE){
                VisitaBuscaMatriz(k,cor,d,f,matriz,tempo);
            }
        }
        cor[u]=2;//2 = preto;
        tempo++;
        f[u]=tempo;
    return;
    }
    
    //Auxiliar para Lista Adjacencia
    
    public void VisitaBuscaLista(int u,int[] cor,int[] d,int[] f,ListaAdjacencia[] LA,int tempo){
        cor[u] = 1;//1 = cinza
        tempo++;
        d[u]=tempo;
        for(int k=0;k<LA[u].getLista().size();k++){
                VisitaBuscaLista(k,cor,d,f,LA,tempo);
        }
        cor[u]=2;//2 = preto;
        tempo++;
        f[u]=tempo;
    return;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscar = new javax.swing.JButton();
        Raiz = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Descoberta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nó Inicial");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vertice", "Tempo de Chegada", "Tempo de Finalização"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Caminho de Descoberta: ");

        Descoberta.setText("caminho");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Buscar))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(10, 10, 10)
                            .addComponent(Descoberta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addGap(1, 1, 1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Raiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Buscar))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Descoberta))
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(tipo==1){
            BuscaProfundidadeMatriz(MA);
        }else if(tipo == 2){
            BuscaProfundidadeLista(LA);
        }
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUBuscaProfundidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUBuscaProfundidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUBuscaProfundidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUBuscaProfundidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUBuscaProfundidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Descoberta;
    private javax.swing.JTextField Raiz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
