/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1grafos;

import Classes.*;
import IU.*;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author AlphaLegends
 */
public class Main extends javax.swing.JFrame {
    MatrizAdjacencia MA = new MatrizAdjacencia();
    ListaAdjacencia[] LA;
    int tipoEstrutura;
    /**
     * Creates new form Main
     */
   
    
    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Guilherme Couto Fernandes       RA 131250671");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Abrir");

        jMenuItem1.setText("Ler Matriz Adjacencia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ler Lista Adjacencia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funções");

        jMenu3.setText("Busca");

        jMenuItem9.setText("Busca em Largura");
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Busca em Profundidade");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenu2.add(jMenu3);

        jMenu4.setText("Arvore Geradora Minima");

        jMenuItem3.setText("Prim");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Kruskal");
        jMenu4.add(jMenuItem4);

        jMenu2.add(jMenu4);

        jMenu5.setText("Caminho Minimo");

        jMenuItem11.setText("Dijkstra");
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Bellman-Ford");
        jMenu5.add(jMenuItem12);

        jMenu2.add(jMenu5);

        jMenuItem5.setText("Verificação de caminho");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Verificação de grafo conexo");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(389, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Grafo");
        file.setFileFilter(new FileFilter(){

            @Override
            public boolean accept(File f) {
                return(f.getName().endsWith(".txt") || f.isDirectory());
            }
            
            @Override
            public String getDescription(){
                return "Arquivo de Texto (.txt)";
            }
        });
            
    int opcao = file.showOpenDialog(this); 
    if(opcao == JFileChooser.APPROVE_OPTION){
        Scanner sc = null;
            try {
                sc = new Scanner(file.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
       
            MA.LerMatrizAdjacencia(sc);
            MA.ExibirMatrizAdjacencia(MA.getMatriz());
            tipoEstrutura = 1;
        
    }
    

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Grafo");
        file.setFileFilter(new FileFilter(){

            @Override
            public boolean accept(File f) {
                return(f.getName().endsWith(".txt") || f.isDirectory());
            }
            
            @Override
            public String getDescription(){
                return "Arquivo de Texto (.txt)";
            }
        });
            
    int opcao = file.showOpenDialog(this);
    
    if(opcao == JFileChooser.APPROVE_OPTION){
        Scanner sc = null;
            try {
                sc = new Scanner(file.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            LerListaAdjacencia(sc);//le a Lista Adjacencia
            ExibirListaAdjacencia();
            tipoEstrutura = 2;
    }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if(tipoEstrutura == 1){
            IUBuscaProfundidade IU = new IUBuscaProfundidade(MA);
            IU.setVisible(true);
        }else if(tipoEstrutura ==2){
            IUBuscaProfundidade IU = new IUBuscaProfundidade(LA);
            IU.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum dado foi carregado");
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables

     public void LerListaAdjacencia(Scanner sc){
        
        int tipoGrafo = sc.nextInt();
        int nVertices = sc.nextInt();
        
        //arraylist
        LA = new ListaAdjacencia[nVertices]; 

        for(int i = 0; i < nVertices; i++){
        LA[i] = new ListaAdjacencia();
        }

        int vertice1;
        int vertice2;
        int peso;

        if(tipoGrafo == 0){//é um grafo, marcar ida e volta
            while(sc.hasNext()){
                int aux;
                //ida
                vertice1 = sc.nextInt();
                vertice2 = sc.nextInt();
                peso = sc.nextInt();
                
                LA[vertice1].setVertice(vertice1);
                LA[vertice1].AdicionarVertice(vertice2,peso);

                //volta
                aux = vertice1;
                vertice1 = vertice2;
                vertice2 = aux;

                LA[vertice1].setVertice(vertice1);
                LA[vertice1].AdicionarVertice(vertice2,peso);
            }
        }else if(tipoGrafo == 1){//é um digrafo, possui orientação, marcar só ida
                while(sc.hasNext()){
                    vertice1 = sc.nextInt();
                    vertice2 = sc.nextInt();
                    peso = sc.nextInt();
                    
                    LA[vertice1].setVertice(vertice1);
                    LA[vertice1].AdicionarVertice(vertice2,peso);
                }        
        }       
    }
    
    private void ExibirListaAdjacencia() {
       for(int i=0;i<LA.length;i++){
           System.out.print(LA[i].exibir());
       }
    }
}
